In [1]:
import tensorflow as tf

创建张量

In [2]:
a = tf.constant([1,5],dtype=tf.int64)
print(a)
print(a.dtype)
print(a.shape)

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


In [3]:
import numpy as np

变换numpy变为tensor

In [4]:
a = np.arange(0,5)
b = tf.convert_to_tensor(a,dtype=tf.int64)
print(b)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


tf.zeros; tf.ones; tf.fill(); 创建0，1，填充值 的张量

In [5]:
a = tf.fill([3,3],3)
print(a)

tf.Tensor(
[[3 3 3]
 [3 3 3]
 [3 3 3]], shape=(3, 3), dtype=int32)


创建正态分布随机数,截断式正态分布随机数（在两倍标准差之内）

In [6]:
a = tf.random.normal([2,2],mean=0.5,stddev=1)
b = tf.random.truncated_normal([2,2],mean=0.5,stddev=1)
print(a)
print(b)

tf.Tensor(
[[-0.1082527  -2.5698225 ]
 [ 0.93717253 -1.1099048 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.6454009  1.1399213 ]
 [1.3144947  0.36801088]], shape=(2, 2), dtype=float32)


生成均匀分布随机数

In [7]:
a = tf.random.uniform([2,2],minval=0,maxval=1)
print(a)

tf.Tensor(
[[0.27872825 0.799261  ]
 [0.39114773 0.54973185]], shape=(2, 2), dtype=float32)


强制转换张量类型，最大值，最小值   tf.cast(张量,dtype=); tf.reduce_min(); tf.reduce_max()

张量求平均，和  tf.reduce_mean(张量,axis=); tf.reduce_sum()

++重要：tf.Variable 将变量标记为可训练的，在反向传播中记录梯度信息

对应元素加减乘除，只能处理相同维度：tf.add; tf.substract; tf.multiply; tf.divide
对应元素平方，乘方，开方：tf.square; tf.pow; tf.sqrt
两个矩阵乘法：tf.matmul()

In [8]:
a = tf.ones([3,2])
b = tf.fill([2,3],3.)
print(a,b,tf.matmul(a,b))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32) tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)
